if(EXISTS "/Users/zhangzhe/Randy/source/Ink/unittests/basics_tests-b858cb2.cmake")
  include("/Users/zhangzhe/Randy/source/Ink/unittests/basics_tests-b858cb2.cmake")
else()
  add_test(basics_NOT_BUILT-b858cb2 basics_NOT_BUILT-b858cb2)
endif()
