if(EXISTS "/Users/zhangzhe/Randy/source/Ink/unittests/c17_graph_tests-b858cb2.cmake")
  include("/Users/zhangzhe/Randy/source/Ink/unittests/c17_graph_tests-b858cb2.cmake")
else()
  add_test(c17_graph_NOT_BUILT-b858cb2 c17_graph_NOT_BUILT-b858cb2)
endif()
