if(EXISTS "/Users/zhangzhe/Randy/source/Ink/unittests/chains_tests-b858cb2.cmake")
  include("/Users/zhangzhe/Randy/source/Ink/unittests/chains_tests-b858cb2.cmake")
else()
  add_test(chains_NOT_BUILT-b858cb2 chains_NOT_BUILT-b858cb2)
endif()
