if(EXISTS "/Users/zhangzhe/Randy/source/Ink/unittests/updated_or_removed_pfxt_nodes_tests-b858cb2.cmake")
  include("/Users/zhangzhe/Randy/source/Ink/unittests/updated_or_removed_pfxt_nodes_tests-b858cb2.cmake")
else()
  add_test(updated_or_removed_pfxt_nodes_NOT_BUILT-b858cb2 updated_or_removed_pfxt_nodes_NOT_BUILT-b858cb2)
endif()
