if(EXISTS "/Users/zhangzhe/Randy/source/Ink/unittests/update_sfxt_tests-b858cb2.cmake")
  include("/Users/zhangzhe/Randy/source/Ink/unittests/update_sfxt_tests-b858cb2.cmake")
else()
  add_test(update_sfxt_NOT_BUILT-b858cb2 update_sfxt_NOT_BUILT-b858cb2)
endif()
